name: solo_social
description: SoloSocial.

version: 0.0.33

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.23.1
  provider: ^4.0.3
  google_fonts: ^0.3.7
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  cloud_firestore: ^0.13.2
  groovin_widgets: ^1.4.2
  avataaar_image: ^1.0.8
  material_design_icons_flutter: ^3.4.4895
  introduction_screen: ^1.0.7
  shared_preferences: ^0.5.6+1
  flutter_signin_button: ^1.0.0
  sentry: ^3.0.1
  timeago: ^2.0.26
  share: ^0.6.3+5
  url_launcher: ^5.4.1
  chips_choice: ^1.0.0
  path_provider: ^1.6.0
  intl: ^0.16.1
  share_extend: ^1.1.1
  file: ^5.1.0
  path_provider_ex: ^1.0.1
  csv: ^4.0.3
  package_info: ^0.4.0+13
  snapfeed: ^0.1.0+1
  permission_handler: ^4.2.0+hotfix.3
  firebase_core: ^0.4.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
