name: solo_social
description: Solitary Social Media
version: 0.2.0+12
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.26.0
  provider: ^5.0.0
  google_fonts: ^2.0.0
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  google_sign_in: ^4.1.1
  cloud_firestore: ^1.0.1
  groovin_widgets: ^2.0.0
  avataaar_image_2: ^2.0.0-dev.3
  material_design_icons_flutter: ^4.0.5955
  introduction_screen: ^2.0.0
  shared_preferences: ^2.0.5
  flutter_signin_button: ^1.0.0
  sentry: ^4.0.6
  timeago: ^3.0.2
  share: ^0.6.3+5
  url_launcher: ^6.0.2
  chips_choice: ^2.0.1
  path_provider: ^2.0.1
  intl: ^0.17.0
  share_extend: ^1.1.1
  file: ^6.1.0
  path_provider_ex: ^1.0.1
  csv: ^4.0.3
  package_info: ^2.0.0
  wiredash: ^0.6.2
  permission_handler: ^4.2.0+hotfix.3
  firebase_crashlytics: ^0.1.3
  keyboard_dismisser: ^1.0.0
  validated: ^1.0.3
  link_previewer:
    git:
      url: https://github.com/GroovinChip/flutter-link-previewer.git
      ref: null_safety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
